services:
  innar:
    image: chrimson/innar:latest
    ports:
      - 5000:5000
    volumes:
      - ./story.txt:/app/story.txt
      - ./auth.json:/app/auth.json
    networks:
      - charlie_default
    restart: always

networks:
  charlie_default:
    external: true
