services:
  innar:
    image: chrimson/innar:latest
    ports:
      - 5000:5000
    volumes:
      - ./:/app/
    networks:
      - charlie_default
    restart: always

networks:
  charlie_default:
    external: true
